import { BlockMath } from 'react-katex';
import 'katex/dist/katex.min.css';

import React from "react";
import { Container } from "react-bootstrap";

function Hobbies() {
  return (
    <Container fluid className="hobbies-section" id="hobbies">
      <Container className="hobbies-content">
        <h4 style={{ fontFamily: 'Inter, Segoe UI, Helvetica Neue, Arial, sans-serif', color: '#f3f3fa', fontSize: '2.2rem', fontWeight: 600, marginBottom: '1.5rem', textAlign: 'center' }}>
          Mathematical Fractals in Julia
        </h4>
        <h6 style={{ fontFamily: 'Inter, Segoe UI, Helvetica Neue, Arial, sans-serif', color: '#e0e0e6', fontSize: '1.15rem', fontWeight: 400, marginBottom: '1.2rem', lineHeight: 1.7 }}>
          Below is the burning ship fractal, generated by iterating the following equation for each point <i>c</i> in the complex plane, starting from the origin:<br /><br />
          <div style={{ display: 'flex', justifyContent: 'center', margin: '1.5rem 0' }}>
            <div style={{ color: '#a259ff', fontSize: '2.38rem', fontWeight: 'bold', width: '100%', textAlign: 'center' }}>
              <BlockMath
                math={"z_{n+1} = (|\\operatorname{Re}(z_n)| + i |\\operatorname{Im}(z_n)|)^2 + c"} 
              />
            </div>
          </div>
          Each pixel is colored according to its 'escape velocity' - how fast the iterative process blows up.<br />
        </h6>
        <div style={{ display: 'flex', justifyContent: 'center', marginTop: '2rem' }}>
          <img src={process.env.PUBLIC_URL + "/Assets/burningship.png"} alt="Burning Ship Fractal" style={{ width: '80vw', maxWidth: '80vw', height: 'auto', borderRadius: '12px', boxShadow: '0 4px 24px rgba(0,0,0,0.3)', display: 'block' }} />
        </div>
      </Container>
    </Container>
  );
}

export default Hobbies;
